### ISSUE TITLE
when logging an error, indicate the request so we can reproduce

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-sequence-retrieval#19]
i see 2:

Detailed Description

java.lang.RuntimeException: Unable to return empty result
       at org.apidb.apicommon.model.report.sequence.SequenceReporter.isWriteEmptyBedFileResponse(SequenceReporter.java:197)
       at org.apidb.apicommon.model.report.sequence.SequenceReporter.write(SequenceReporter.java:131)
       at org.gusdb.wdk.model.report.AbstractReporter.report(AbstractReporter.java:57)
       at org.gusdb.wdk.service.service.AnswerService.lambda$getAnswerAsStream$5(AnswerService.java:469)

Detailed Description

org.gusdb.wdk.model.WdkModelException: Genomic segment ID CABPSV020000001:-2038--2022:r not matching pattern ^(.*):(\d+)-(\d+):(f|r)$
       at org.apidb.apicommon.model.report.bed.feature.DynSpanFeatureProvider.getRecordAsBedFields(DynSpanFeatureProvider.java:47)
       at org.apidb.apicommon.model.report.bed.BedReporter.write(BedReporter.java:103)
       at org.gusdb.wdk.model.report.AbstractReporter.report(AbstractReporter.java:57)

**Comment by aurreco-uga** [comment]
i think the new title describes the issue better, not sure what was that specific error.
THIS IS NOT URGENT since we have the request in wd-service logs
